apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-rollouts/releases/download/v1.1.1/install.yaml
namespace: argo-rollouts
commonAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "8090"
